### ISSUE TITLE
Not working on PrestaShop 1.7.4.2

### ISSUE THREAD

**Issue by 0568595** [payfort/prestashop-payfort#11]
Dear payfort support

the module not working in PrestaShop 1.7.4.2 and not appear in payment options , 

can you please kindly fix the issues ....?

**Comment by mohannadsaleh** [comment]
Hi ,

Thank you for reaching out , we will be working on our plugin to make it compatible with the new version of PrestaShop , we will keep you posted , 

also please feel free to watch our repo to get directly notification once we release the compatibility  changes 

Mohannad

**Comment by mohannadsaleh** [comment]
This is to update you that we have launched prestashop 1.7 you can find it under the same gihub rep listing please find the below link 

https://github.com/payfort/prestashop1.7-payfort

Please share with us your feedback .
Best Regards,
Mohanad
