### ISSUE TITLE
Payfort is not showing in checkout payment options

### ISSUE THREAD

**Issue by sudheeshde** [payfort/prestashop-payfort#2]
Yesterday I configured payfort into my prestashop store, but when going to checkout, it doesn't shows payfort checkout. So, what could be gone wrong ? Please advice asap.

**Comment by sudheeshde** [comment]
we installed your plugin and it appears in module list but the plugin is not getting recognized as a payment method inside prestashop..

**Comment by mohannadsaleh** [comment]
Hi 

Thank you for contacting us on github , please contact integration team at integration@payfort.com , they will be supporting you during the integration and installation with the FORT system .

Best Regards,
Mohannad Saleh
