### ISSUE TITLE
Not working on PrestaShop 1.7.4

### ISSUE THREAD

**Issue by saud978** [payfort/prestashop-payfort#9]
This version of payfort is not working on prestashop 1.7.4.0
I can't see the module in modules list nor in payment tap.

**Comment by PayFortIntegration** [comment]
Hi Saud, 
Can you please email us on integration@payfort.com and share with us the issue you experience ? 
This is in order to assist you properly. 

Thanks
Esraa

**Comment by saud978** [comment]
I follow the installation steps but can't see the plugin in my prestashop dashboard.
I installed this plugin on fresh installation of prestashop 1.7.4.0

**Comment by PayFortIntegration** [comment]
Hi Saud,
Please make sure to download our supported ready module from the following URL :
https://github.com/payfort/prestashop-payfort

Then there will be specific steps we need you to follow them in order to integrate properly.
for that we asked you to email us on integration@payfort.com

Thanks
Esraa

**Comment by stpnwolf-hub** [comment]
@saud978 You cant currently see the module in Prestashop 1.7.4 as the module is currently developed for previous 1.6.x versions and is not compatible with the last version of prestashop.
@PayFortIntegration Can you let us know when you are planning to upgrade your module? there are many people outside waiting so we can upgrade our Prestashop to the last version
Thx

**Comment by mohannadsaleh** [comment]
Hi @saud978 ,

Thank you for your valuable feedback , currently the plugin still not supporting 1.7 
we arrange for supporting 1.7.x versions in our road map and will update you with the release date once confirmed . 

Thank you again , and please feel free to contact us if we can be any help in the mean while .

Mohannad

**Comment by jlamloum** [comment]
Hi @mohannadsaleh,

Any ETA regarding this project? Our current upgrade project is being held as Payfort is the last module not compatible 1.7

Thanks a lot

**Comment by mohannadsaleh** [comment]
We have launched the prestashop 1.7 plugin please find below link 
https://github.com/payfort/prestashop1.7-payfort

Please share with us your feedback 
Best Regards,
Mohanad
